name: Build

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [8, 10, 12]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run format:check
      - run: npm run lint
      - run: npm run build
      - run: npm run test
