name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
        node: [10, 12]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run format:check
      - run: npm run lint
      - run: npm run build
      - run: npm run test

  build-examples:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [10, 12]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run build:image --prefix examples/cli
      - run: npm run build:image --prefix examples/express
      - run: npm run build:image --prefix examples/express-static

  publish:
    needs: [build, build-examples]
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/

      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
